[package]
name = "sourcesvn"
version = "0.1.0"
description = "轻量级 SVN GUI 客户端"
authors = ["you"]
edition = "2021"

[lib]
name = "sourcesvn_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
quick-xml = { version = "0.36", features = ["serialize"] }
reqwest = { version = "0.12", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
sha2 = "0.10"
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
log = "0.4"
env_logger = "0.11"
dirs = "5"
toml = "0.8"
futures-util = "0.3"
encoding_rs = "0.8"
windows-sys = { version = "0.59", features = ["Win32_System_Console"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
